package com.stewsters.samurai;		
import java.util.Random;

import com.stewsters.samurai.enums.Gender;
import com.stewsters.samurai.enums.SocialClass;

public class NameGenerator
{

	public static boolean female = false;
	public static boolean male = true;
	
	public static String getName(SocialClass type, Gender gender)
	{
		Random r = new Random();
		String name = "none";
		if(type == SocialClass.SAMURAI)
		{
			name = samuraiFamilyNames[r.nextInt(NameGenerator.samuraiFamilyNames.length)];
		}
		return name;
	}
	
	
	//family name, given name
	static String[] samuraiFamilyNames ={
		"Abe Katsuyoshi",
		"Abe Masakatsu",
		"Adachi Yasumori",
		"Adachi Kagemori",
		"Aiou Mototsuna",
		"Marise Kagekatsu Ayame Kagekatsu",
		"Akechi Mitsuhide",
		"Akao Kiyotsuna",
		"Amago Haruhisa",
		"Amago Yoshihisa",
		"Ankokuji Ekei",
		"Aochi Shigetsuna",
		"Aokage Takaakira",
		"Aoki Kazushige",
		"Arai Hakuseki",
		"Araki Motokiyo",
		"Araki Murashige",
		"Araki Muratsugu",
		"Arima Kihei",
		"Asakura Yoshikage",
		"Azai Hisamasa",
		"Azai Nagamasa",
		"Azai Sukemasa",
		"Baba Nobufusa",
		"Bessho Nagaharu",
		"Chosokabe Morichika",
		"Chosokabe Motochika",
		"Chosokabe Nobuchika",
		"Date Masamune",
		"Doi Toshikatsu",
		"Endo Naotsune",
		"Enjoji Nobutane",
		"Enomoto Takeaki",
		"Era Fusahide",
		"Fuwa Mitsuharu",
		"Gamo Katahide",
		"Gamo Ujisato",
		"Harada Naomasa",
		"Hasekura Tsunenaga",
		"Hattori Hanzo",
		"Hashiba Hideyoshi",
		"Hatano Hideharu",
		"Hasegawa Eishin",
		"Hayashizaki Jinsuke Shigenobu",
		"Hirate Masahide",
		"Hitotsubashi Keiki",
		"Hōjō Masako",
		"Hōjō Tokimune",
		"Hōjō Ujiyasu",
		"Honda Tadakatsu",
		"Hosokawa Fujitaka",
		"Hosokawa Gracia",
		"Hosokawa Tadaoki",
		"Hotta Masatoshi",
		"Ichi",
		"Ii Naoaki",
		"Ii Naomasa",
		"Ii Naomori",
		"Ii Naonaka",
		"Ii Naosuke",
		"Ii Naotaka",
		"Ii Naoyuki",
		"Ii Naozumi",
		"Iizasa Ienao",
		"Ijuin Tada'aki",
		"Imagawa Yoshimoto",
		"Imai Kanehira",
		"Inugami Nagakatsu",
		"Ishida Mitsunari",
		"Isshiki Fujinaga",
		"Itagaki Nobukata",
		"Ito Hirobumi",
		"Iwanari Tomomichi",
		"Jinbo Kiyoshige",
		"Jinbo Nagakiyo",
		"Jinbo Nagamoto",
		"Jinbo Nagatsuna",
		"Jinbo Yoshikata",
		"Kaneko Ietada",
		"Katagiri Katsumoto",
		"Kataoka Mitsumasa",
		"Kato Kiyomasa",
		"Kawakami Gensai",
		"Kido Takayoshi",
		"Kikkawa Hiroie",
		"Kimotsuki Kanetsugu",
		"Kobayakawa Hideaki",
		"Kobayakawa Hidekane",
		"Kobayakawa Takakage",
		"Kuroda Hanbei",
		"Kuroda Kiyotaka",
		"Kuroda Yoshitaka",
		"Kusunoki Masashige",
		"Kuwana Tarozaemon",
		"Kumagai Naozane",
		"Maeda Keiji",
		"Maeda Nagatane",
		"Maeda Toshiie",
		"Maeda Toshinaga",
		"Maeda Toshitsune",
		"Magome Kageyu",
		"Manabe Akifusa",
		"Matsudaira Nobutsuna",
		"Matsudaira Higo no Kami Katamori",
		"Matsudaira Sadanobu",
		"Matsudaira Teru",
		"Matsunaga Hisahide",
		"Matsunaga Hisamichi",
		"Matsuo Bashō",
		"Matsudaira Motoyasu",
		"Minamoto no Mitsunaka",
		"Minamoto no Yoshiie",
		"Minamoto no Yoshimitsu",
		"Minamoto no Yoshinaka",
		"Minamoto no Yoshitomo",
		"Minamoto no Yoshitsune",
		"Minamoto no Tameyoshi",
		"Minamoto no Yorimasa",
		"Minamoto no Yorimitsu",
		"Minamoto no Yoritomo",
		"Minamoto no Noriyori",
		"Miura Anjin",
		"Miura Yoshimoto",
		"Miyamoto Musashi",
		"Miyoshi Chokei",
		"Miyoshi Kazuhide",
		"Miyoshi Masaga",
		"Miyoshi Masayasu",
		"Miyoshi Moriyata",
		"Miyoshi Nagayuki",
		"Miyoshi Yoshitsugu",
		"Mizuno Tadakuni",
		"Moniwa Yoshinao",
		"Mori Motonari",
		"Mori Nagasada",
		"Mori Nagayoshi",
		"Mori Okimoto",
		"Mori Ranmaru",
		"Mori Takamoto",
		"Mori Tadamasa",
		"Mori Terumoto",
		"Mori Yoshinari",
		"Nagakura Shinpachi",
		"Nagao Harukage",
		"Nagao Kagenobu",
		"Nagao Masakage",
		"Nagao Tamekage",
		"Nakagawa Kiyohide",
		"Nakajima Bungo",
		"Nanbu Yasunobu",
		"Naoe Kagetsuna",
		"Naoe Kanetsugu",
		"Nihonmatsu Yoshitsugu",
		"Niimi Nishiki",
		"Niiro Tadamoto",
		"Niwa Nagahide",
		"Niwa Nagashige",
		"Oda Hiroyoshi",
		"Oda Nobuhide",
		"Oda Nobukata",
		"Oda Nobukiyo",
		"Oda Nobunaga",
		"Oda Nobutada",
		"Oda Nobutomo",
		"Oda Nobukatsu",
		"Oda Nobuyasu",
		"Ogasawara Shosai",
		"Oishi Kuranosuke",
		"Judge Ooka",
		"Okita Soji",
		"Okubo Toshimichi",
		"Okunomiya Masaie",
		"Ōuchi Yoshitaka",
		"Reizei Takatoyo",
		"Rokkaku Sadayori",
		"Rokkaku Yoshiharu",
		"Rokkaku Yoshitaka",
		"Rusu Masakage",
		"Sagara Taketo",
		"Saigō Takamori",
		"Saitō Dōsan",
		"Saito Hajime",
		"Saito Musashibo Benkei",
		"Saito Yoshitatsu",
		"Sakai Tadakiyo",
		"Sakai Tadashige",
		"Sakai Tadayo",
		"Sakamoto Ryoma",
		"Sakuma Morimasa",
		"Sakuma Nobumori",
		"Sanada Masayuki",
		"Sanada Nobuyuki",
		"Sanada Yukimura",
		"Sasaki Kojiro",
		"Serizawa Kamo",
		"Shibata Katsuie",
		"Shima Sakon",
		"Shimada Ichiro",
		"Shimazu Katsuhisa",
		"Shimazu Tadahisa",
		"Shimazu Tadatsune",
		"Shimazu Tadayoshi",
		"Shimazu Takahisa",
		"Shimazu Yoshihiro",
		"Shimazu Yoshihisa",
		"Shindou Hiroshii",
		"Sogo Nagayasu",
		"Taigen Sessai",
		"Taira no Kiyomori",
		"Taira Masakado",
		"Takahashi Shigetane",
		"Takasugi Shinsaku",
		"Takayama Justo",
		"Takayama Ukon",
		"Takeda Katsuyori",
		"Takeda Nobukatsu",
		"Takeda Nobushige",
		"Takeda Shingen",
		"Tani Tadasumi",
		"Toki Yorinari",
		"Tokugawa Ieyasu",
		"Tokugawa Hidetada",
		"Tokugawa Nariaki",
		"Tokugawa Yoshinobu",
		"Toyotomi Hideyoshi",
		"Toyotomi Hideyori",
		"Tsukahara Bokuden",
		"Uesugi Kagekatsu",
		"Uesugi Kagetora",
		"Uesugi Kenshin",
		"Ujiie Naomoto",
		"Ukita Naoie",
		"Ukita Okiie",
		"Umezawa Michiharu",
		"Usami Sadamitsu",
		"Uyama Hisanobu",
		"Wada Shinsuke",
		"Watanabe no Tsuna",
		"Yagyu Jubei Mitsuyoshi",
		"Yasuke",
		"Yamada Arinaga",
		"Yamada Arinobu",
		"Yamada Nagamasa",
		"Yamagata Masakage",
		"Yamanami Keisuke",
		"Yanagisawa Yoshiyasu",
		"Yonekura Shigetsugu",
		"Yagyu Munenori",
		"Yamauchi Kazutoyo"
	};
	
	static String[] samuraiGivenNames ={
		"Abe Katsuyoshi",
		"Abe Masakatsu",
		"Adachi Yasumori",
		"Adachi Kagemori",
		"Aiou Mototsuna",
		"Marise Kagekatsu Ayame Kagekatsu",
		"Akechi Mitsuhide",
		"Akao Kiyotsuna",
		"Amago Haruhisa",
		"Amago Yoshihisa",
		"Ankokuji Ekei",
		"Aochi Shigetsuna",
		"Aokage Takaakira",
		"Aoki Kazushige",
		"Arai Hakuseki",
		"Araki Motokiyo",
		"Araki Murashige",
		"Araki Muratsugu",
		"Arima Kihei",
		"Asakura Yoshikage",
		"Azai Hisamasa",
		"Azai Nagamasa",
		"Azai Sukemasa",
		"Baba Nobufusa",
		"Bessho Nagaharu",
		"Chosokabe Morichika",
		"Chosokabe Motochika",
		"Chosokabe Nobuchika",
		"Date Masamune",
		"Doi Toshikatsu",
		"Endo Naotsune",
		"Enjoji Nobutane",
		"Enomoto Takeaki",
		"Era Fusahide",
		"Fuwa Mitsuharu",
		"Gamo Katahide",
		"Gamo Ujisato",
		"Harada Naomasa",
		"Hasekura Tsunenaga",
		"Hattori Hanzo",
		"Hashiba Hideyoshi",
		"Hatano Hideharu",
		"Hasegawa Eishin",
		"Hayashizaki Jinsuke Shigenobu",
		"Hirate Masahide",
		"Hitotsubashi Keiki",
		"Hōjō Masako",
		"Hōjō Tokimune",
		"Hōjō Ujiyasu",
		"Honda Tadakatsu",
		"Hosokawa Fujitaka",
		"Hosokawa Gracia",
		"Hosokawa Tadaoki",
		"Hotta Masatoshi",
		"Ichi",
		"Ii Naoaki",
		"Ii Naomasa",
		"Ii Naomori",
		"Ii Naonaka",
		"Ii Naosuke",
		"Ii Naotaka",
		"Ii Naoyuki",
		"Ii Naozumi",
		"Iizasa Ienao",
		"Ijuin Tada'aki",
		"Imagawa Yoshimoto",
		"Imai Kanehira",
		"Inugami Nagakatsu",
		"Ishida Mitsunari",
		"Isshiki Fujinaga",
		"Itagaki Nobukata",
		"Ito Hirobumi",
		"Iwanari Tomomichi",
		"Jinbo Kiyoshige",
		"Jinbo Nagakiyo",
		"Jinbo Nagamoto",
		"Jinbo Nagatsuna",
		"Jinbo Yoshikata",
		"Kaneko Ietada",
		"Katagiri Katsumoto",
		"Kataoka Mitsumasa",
		"Kato Kiyomasa",
		"Kawakami Gensai",
		"Kido Takayoshi",
		"Kikkawa Hiroie",
		"Kimotsuki Kanetsugu",
		"Kobayakawa Hideaki",
		"Kobayakawa Hidekane",
		"Kobayakawa Takakage",
		"Kuroda Hanbei",
		"Kuroda Kiyotaka",
		"Kuroda Yoshitaka",
		"Kusunoki Masashige",
		"Kuwana Tarozaemon",
		"Kumagai Naozane",
		"Maeda Keiji",
		"Maeda Nagatane",
		"Maeda Toshiie",
		"Maeda Toshinaga",
		"Maeda Toshitsune",
		"Magome Kageyu",
		"Manabe Akifusa",
		"Matsudaira Nobutsuna",
		"Matsudaira Higo no Kami Katamori",
		"Matsudaira Sadanobu",
		"Matsudaira Teru",
		"Matsunaga Hisahide",
		"Matsunaga Hisamichi",
		"Matsuo Bashō",
		"Matsudaira Motoyasu",
		"Minamoto no Mitsunaka",
		"Minamoto no Yoshiie",
		"Minamoto no Yoshimitsu",
		"Minamoto no Yoshinaka",
		"Minamoto no Yoshitomo",
		"Minamoto no Yoshitsune",
		"Minamoto no Tameyoshi",
		"Minamoto no Yorimasa",
		"Minamoto no Yorimitsu",
		"Minamoto no Yoritomo",
		"Minamoto no Noriyori",
		"Miura Anjin",
		"Miura Yoshimoto",
		"Miyamoto Musashi",
		"Miyoshi Chokei",
		"Miyoshi Kazuhide",
		"Miyoshi Masaga",
		"Miyoshi Masayasu",
		"Miyoshi Moriyata",
		"Miyoshi Nagayuki",
		"Miyoshi Yoshitsugu",
		"Mizuno Tadakuni",
		"Moniwa Yoshinao",
		"Mori Motonari",
		"Mori Nagasada",
		"Mori Nagayoshi",
		"Mori Okimoto",
		"Mori Ranmaru",
		"Mori Takamoto",
		"Mori Tadamasa",
		"Mori Terumoto",
		"Mori Yoshinari",
		"Nagakura Shinpachi",
		"Nagao Harukage",
		"Nagao Kagenobu",
		"Nagao Masakage",
		"Nagao Tamekage",
		"Nakagawa Kiyohide",
		"Nakajima Bungo",
		"Nanbu Yasunobu",
		"Naoe Kagetsuna",
		"Naoe Kanetsugu",
		"Nihonmatsu Yoshitsugu",
		"Niimi Nishiki",
		"Niiro Tadamoto",
		"Niwa Nagahide",
		"Niwa Nagashige",
		"Oda Hiroyoshi",
		"Oda Nobuhide",
		"Oda Nobukata",
		"Oda Nobukiyo",
		"Oda Nobunaga",
		"Oda Nobutada",
		"Oda Nobutomo",
		"Oda Nobukatsu",
		"Oda Nobuyasu",
		"Ogasawara Shosai",
		"Oishi Kuranosuke",
		"Judge Ooka",
		"Okita Soji",
		"Okubo Toshimichi",
		"Okunomiya Masaie",
		"Ōuchi Yoshitaka",
		"Reizei Takatoyo",
		"Rokkaku Sadayori",
		"Rokkaku Yoshiharu",
		"Rokkaku Yoshitaka",
		"Rusu Masakage",
		"Sagara Taketo",
		"Saigō Takamori",
		"Saitō Dōsan",
		"Saito Hajime",
		"Saito Musashibo Benkei",
		"Saito Yoshitatsu",
		"Sakai Tadakiyo",
		"Sakai Tadashige",
		"Sakai Tadayo",
		"Sakamoto Ryoma",
		"Sakuma Morimasa",
		"Sakuma Nobumori",
		"Sanada Masayuki",
		"Sanada Nobuyuki",
		"Sanada Yukimura",
		"Sasaki Kojiro",
		"Serizawa Kamo",
		"Shibata Katsuie",
		"Shima Sakon",
		"Shimada Ichiro",
		"Shimazu Katsuhisa",
		"Shimazu Tadahisa",
		"Shimazu Tadatsune",
		"Shimazu Tadayoshi",
		"Shimazu Takahisa",
		"Shimazu Yoshihiro",
		"Shimazu Yoshihisa",
		"Shindou Hiroshii",
		"Sogo Nagayasu",
		"Taigen Sessai",
		"Taira no Kiyomori",
		"Taira Masakado",
		"Takahashi Shigetane",
		"Takasugi Shinsaku",
		"Takayama Justo",
		"Takayama Ukon",
		"Takeda Katsuyori",
		"Takeda Nobukatsu",
		"Takeda Nobushige",
		"Takeda Shingen",
		"Tani Tadasumi",
		"Toki Yorinari",
		"Tokugawa Ieyasu",
		"Tokugawa Hidetada",
		"Tokugawa Nariaki",
		"Tokugawa Yoshinobu",
		"Toyotomi Hideyoshi",
		"Toyotomi Hideyori",
		"Tsukahara Bokuden",
		"Uesugi Kagekatsu",
		"Uesugi Kagetora",
		"Uesugi Kenshin",
		"Ujiie Naomoto",
		"Ukita Naoie",
		"Ukita Okiie",
		"Umezawa Michiharu",
		"Usami Sadamitsu",
		"Uyama Hisanobu",
		"Wada Shinsuke",
		"Watanabe no Tsuna",
		"Yagyu Jubei Mitsuyoshi",
		"Yasuke",
		"Yamada Arinaga",
		"Yamada Arinobu",
		"Yamada Nagamasa",
		"Yamagata Masakage",
		"Yamanami Keisuke",
		"Yanagisawa Yoshiyasu",
		"Yonekura Shigetsugu",
		"Yagyu Munenori",
		"Yamauchi Kazutoyo"
	};
}


